server.port=${PORT:3003}
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DB:cuentas_claras}
# Swagger UI en /docs  |  JSON OpenAPI en /openapi.json
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/openapi.json
